### ISSUE TITLE
Compile error: no member named 'hock_schittkowsky_71' in namespace 'pagmo'

### ISSUE THREAD

**Issue by xand-stapleton** [esa/pygmo2#106]
When compiling from source on any architecture (tested on Intel MacOS 12.6, M1 MacOS 12.6 and x86/64Arch Linux kernel 5.19.12), compile fails with error:
 error: no member named 'hock_schittkowsky_71' in namespace 'pagmo'

The name of the pagmo library changed as of https://github.com/esa/pagmo2/commit/8f95308ce9a70b12d1b0b3a63fc3aa7dce6d143b

All references in the file 'expose_problems_0.cpp' must be changed from 'hock_schittkowsky' to 'hock_schittkowski' to compile, and be compatible to the latest current git version on the master branch.

**Comment by bluescarni** [comment]
@xand-stapleton yep you are perfectly right. I'll open a PR.

**Comment by xand-stapleton** [comment]
Thanks :)

**Comment by bluescarni** [comment]
This should now be fixed by #107 . Please re-open if needed.
