### ISSUE TITLE
[BUG] Error raising while running the tests right after installation

### ISSUE THREAD

**Issue by IgSMS** [esa/pygmo2#118]
**Describe the bug**
After installing pygmo via conda installer I executed the command `pygmo.test.run_test_suite()`, however, the installation seems to have failed due to some errors arising as outputs. I installed pygmo in a new environment with Python 3.9.12 only. Afterwards, I installed Spyder to use as the IDE. 

Three tests are failing due to the exact same error: `NotImplementedError: pool objects cannot be passed between processes or pickled`, found on .. \lib\multiprocessing\pool.py.

I have uninstalled and installed again, as well as updating, but the same errors keep appearing.

On the other hand, another error is found on test ´pygmo.test.decorator_problem_test_case´, being the error: `AttributeError: 'NoneType' object has no attribute 'dv_log'`. 

**To Reproduce**
1. Create a new Anaconda environment with Python 3.9.12.
2. Write on CMD prompt: `conda install pygmo`.
3. Install Spyder IDE.
4. Write on command window: `import pygmo`, `pygmo.test.run_test_suite()`
5. See errors

**Expected behavior**
I expected to see no errors since I followed installation steps and checked whether the dependencies where also installed.

**Environment (please complete the following information):**
 - OS: Windows-64
 - Installation method: conda
 - Conda version: 4.12.0
 - Conda-build version: 3.21.8
 - Python version: 3.9.12.final.0

**Comment by darioizzo** [comment]
Is this related to #116? Maybe you can try to run with that dill version and see if it fixes the problem. 
I think this will anyway be solved in the next (upcoming) release.

**Comment by IgSMS** [comment]
Okay, I will try running it with a different dill version.  Also, do you think the AttributeError is related to the previous errors, or its nature is different?

**Comment by IgSMS** [comment]
> 

Using Dill's version 0.3.5.1 actually worked! Thank you very much for your help.
