### ISSUE TITLE
[BUG] Problem Serializing `pg.problem()` 

### ISSUE THREAD

**Issue by IgSMS** [esa/pygmo2#123]
**Describe the bug**
When I try to serialiaze my pygmo problem, let's say `pg.problem(udp=my_udp(arguments))`, an error is raised saying that I am not able to serialize weakref objects. I have been inspecting if `my_udp(arguments)` was the cause, but it is not since it can be serialized. On the other hand, `pg.problem()` without arguments can also be serialized. The issue appears when I try both at once.

This is happening in the context of trying to evolve the population using an archipelago.

**Expected behavior**
The status of the different islands should be idle, not an error.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Installation method: conda
 - Version: 2.19

Thank you very much for your help!

**Comment by bluescarni** [comment]
Gonna close this one and continue the discussion in #83 .
