### ISSUE TITLE
[FEATURE] Support ARM from Pypi

### ISSUE THREAD

**Issue by ccrutchf** [esa/pygmo2#128]
**Is your feature request related to a problem? Please describe.**
Since AWS and other cloud providers provide cheaper platform support for ARM, is it possible to create a wheel for ARM to support pygmo on ARM?

**Describe the solution you'd like**
Add a Pypi wheel for ARM.

**Describe alternatives you've considered**
Conda is, unfortunately, not an option since we are integrating into existing systems using Pip.

**Additional context**
Would a pull request be accepted to support building ARM wheels?

**Comment by bluescarni** [comment]
@ccrutchf yes it would be great if you could open a pull request for ARM wheels.

I would imagine the infrastructure already there for x86-64 builds can largely be reused - perhaps it's just a matter of changing the docker image and the github actions runner?

**Comment by ccrutchf** [comment]
Thanks @bluescarni!

I have created a PR on esa/manylinux_x86_64_with_deps to prepare to build ARM wheels using the existing GitHub actions runner.  I also have a branch that builds the wheel based on the update to the docker container, which I'll open a PR for once I can update it with the official docker container.

**Comment by bluescarni** [comment]
Will close this as the arm64 wheels are now available.
