### ISSUE TITLE
Documentation of parallel processing of individual fitness function evaluations

### ISSUE THREAD

**Issue by mike-slackenerny** [esa/pygmo2#13]
I have been tinkering with pygmo to automate the optimisation of a 3D structure in an electromagnetism problem. The evaluation of the fitness function can take up to 1h on an AWS cluster. In this type of problem, sequential computation of generations of more than a couple of individuals is out of the question. The batch parallel initialization helps, but it is of course just the first step.

I was wondering if any of the algorithms in the library could use this same parallel evaluation for subsequent generations, or whether it would be possible to launch individual evaluations in parallel through the existing mp/thread/ipyparallel based classes. As long as the calculation of the parameters of the individuals in a generation do not depend from the results of previous members of their generation, I guess this should work.

**Comment by sertho** [comment]
Hi
Thank you for your amazing work PyGMO!
I just published a question on stackexchange regarding this topic:
[https://stackoverflow.com/questions/60435885/pygmo-batch-fitness-evaluation](https://stackoverflow.com/questions/60435885/pygmo-batch-fitness-evaluation)

Would be nice if in the meantime somebody could give a short example as answer on that question?

**Comment by bluescarni** [comment]
I have replied on SO.
