### ISSUE TITLE
Add source distribution to pip

### ISSUE THREAD

**Issue by Balandat** [esa/pygmo2#32]
Would it be possible add a source distribution to the pip package?

**Comment by darioizzo** [comment]
any idea on how thats done?

**Comment by Balandat** [comment]
Sure, it's described in this tutorial: https://packaging.python.org/tutorials/packaging-projects/

What you're looking for is `sdist`, as in `python3 setup.py sdist bdist_wheel`.

**Comment by johnnymck** [comment]
#55 Created a PR for this issue. Please let me know if this is at all useful.

Cheers :)

**Comment by darioizzo** [comment]
Closing this. Its not possible to have source code uploaded to pypi as platform independent. Only wheels can be made for each platform. For any linux this is now activated again via #117 and will be available at the next release.
