### ISSUE TITLE
NSPSO doesn't work correctly with integer variables

### ISSUE THREAD

**Issue by Tomalwo** [esa/pygmo2#37]
In my tests, NSPSO doesn't appear to work correctly with integer variables:

After the first population, which works fine, subsequent populations have non-integer values even for "integer" variables.

The same is true for MOEA/D, but, according to the [documentation](https://esa.github.io/pygmo2/overview.html#list-of-algorithms), it doesn't handle integers.
So perhaps the issue is not with the implementation of NSPO, but with the [documentation](https://esa.github.io/pygmo2/overview.html#list-of-algorithms)?

Thanks!
Thomas

PS: With NSGA-II, integer handling works fine, which is why I think that the issue isn't on my end.

**Comment by darioizzo** [comment]
Indded thanks for the report. In the docs the algortihm should be marked as M-U not M-U-I @bluescarni has a PR opened that may include this change maybe?

**Comment by bluescarni** [comment]
Thanks for the report, I'll fold the changes in esa/pagmo2#410.

**Comment by bluescarni** [comment]
Closing this as the docs have been update in both PRs.
