### ISSUE TITLE
Expose crossover and mutation C++ operators in Python

### ISSUE THREAD

**Issue by MLopez-Ibanez** [esa/pygmo2#43]
Would it be possible to expose the various crossover and mutation operators in Python:

Crossover: four different crossover schemes are provided:single, exponential, binomial, sbx.
Mutation: three different mutations schemes are provided: uniform, gaussian and polynomial. 

https://esa.github.io/pygmo2/algorithms.html?highlight=sbx

We would like to reuse them to implement our own UDAs.

**Comment by bluescarni** [comment]
I have partially replied to this in esa/pagmo2#419. Before being able to expose the operators, we need to implement them on the C++ side.

**Comment by MLopez-Ibanez** [comment]
> I have partially replied to this in [esa/pagmo2#419](https://github.com/esa/pagmo2/issues/419). Before being able to expose the operators, we need to implement them on the C++ side.

Just a note that they are now implemented on the C++ side, so this could move forward.

**Comment by MLopez-Ibanez** [comment]
Hi,

What is stopping this to be merged and closed?

**Comment by darioizzo** [comment]
I assume you refer to the PR #51. The review from @bluescarni needs to be implemented. See the PR.

**Comment by bluescarni** [comment]
#51 has been merged, I will go ahead and close this report.
