### ISSUE TITLE
Jointly use PyTorch and Pygmo

### ISSUE THREAD

**Issue by Ssicayoon** [esa/pygmo2#54]
When I try to use pytoch and pygmo jointly, the `RuntimeError: Unable to cast Python instance to C++ type` occours.

1) Is there a way to use pytorch in pygmo?

2) Should I use pagmo instead, with c++ of pytorch, because the error is the cast from python to c++?

**Comment by bluescarni** [comment]
@Ssicayoon it's not possible for us to help you without more specific info. Perhaps you can come over to the gitter channel, where it might be easier to have a discussion?

https://gitter.im/pagmo2/Lobby

**Comment by Ssicayoon** [comment]
@bluescarni Thanks for your reply!
I have found and fixed the problem, the wrong data type `tensor` for Pygmo functions.
