### ISSUE TITLE
2.16 release

### ISSUE THREAD

**Issue by arita37** [esa/pygmo2#57]
Just wondering when you wish to release 2.16 ?
Can we add manually in the code the 2.15 --> 2.16 changes in the sites-package source code ?

**Comment by darioizzo** [comment]
It is not recommended to make the changes manually as they may be tied up also with the pagmo c++ library and other dependencies.

You can, though, compile and install pagmo and pygmo in your conda environment from source.

We typically release the new version either when there are enough changes accumulated, or each ~6 months to try and maintain the CI workflow. This has not been discussed yet with the core developers, but I think you may expect a new release in the Sept-Oct timeframe.

**Comment by arita37** [comment]
2.16 is mostly scipy integration...
Scipy is high level api...

**Comment by bluescarni** [comment]
pagmo/pygmo 2.16 have been released, closing this report.
