### ISSUE TITLE
Cannot import from Conda

### ISSUE THREAD

**Issue by VallesMarinerisExplorer** [esa/pygmo2#68]
Hi, I am trying to import pygmo from Conda. I used the Anaconda prompt on my windows 10 machine. I didn't have any luck with the install directions in the docs so I tried the first one here:

https://anaconda.org/conda-forge/pygmo

conda install -c conda-forge pygmo

(base) C:\Users\Alex>conda install -c conda-forge pygmo
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \

Goes on continuously.

I tried removing conda forge to no avail, per the suggestion here.

https://github.com/conda/conda/issues/8051

Would it be possible to have a pygmo binary for windows 10?

Thanks!

Alex

**Comment by bluescarni** [comment]
Hi Alex,

this looks like a conda problem. Can you try to install ``mamba`` from conda-forge and use that to install pygmo instead? E.g., something like:

```console
conda install -c conda-forge mamba
mamba install -c conda-forge pygmo
```

**Comment by fialat** [comment]
Creating a new environment solved this issue for me. @merv provided a very nice answer here: https://stackoverflow.com/questions/67471968/conflicts-during-pygmo-installation-on-mac-os-x-11-2-2-with-anaconda

**Comment by bluescarni** [comment]
I will close this report for the time being, please re-open if needed @VallesMarinerisExplorer .
