### ISSUE TITLE
MOEAD algorithm: crashes in windows enviroment (pip package)

### ISSUE THREAD

**Issue by vathomass** [esa/pygmo2#7]
Hi,
Just trying to deploy the moead with a already existing  udp (`pygmo.dtlz` for example) in windows results in crashing python (Python 3.6.6).  The interpreter exits to the windows terminal without any message, after one generation (if I enable verbosity of the algorithm, I get one log line).

The exact same script is able to run in Linux (Linux 5.0.8-arch1-1-ARCH x86_64 GNU/Linux), but with issue esa/pagmo2#357 .

Best,
Thomas

**Comment by bluescarni** [comment]
I'll close this report for the time being, as the pip packages for Windows are not being produced any more.
