### ISSUE TITLE
[FEATURE] ARM support, is it possible?

### ISSUE THREAD

**Issue by Epse** [esa/pygmo2#72]
**Is your feature request related to a problem? Please describe.**
I work on a Wi-Fi fuzzing appliance, which is being ported to an ARM platform, is it possible to use pygmo on ARM? Install via pip doesn't work for obvious reasons

**Comment by bluescarni** [comment]
@Epse porting pygmo/pagmo to ARM should be straightforward, as there is essentially no platform-specific code in either library.

After this is done, we should enable ARM builds for pagmo/pygmo in conda-forge. This also should not be an issue. Once this is done, you should be able to install the ARM version of pygmo via miniforge:

https://github.com/conda-forge/miniforge

I don't anticipate having the bandwidth to maintain a pip ARM build, unless someone from the community is willing to step up.

I'll put this in the TODO list for the next pagmo/pygmo version, but it will take some time.

**Comment by bluescarni** [comment]
@Epse pagmo/pygmo 2.18 now support ARM and PowerPC processors. Conda packages for these architectures should be available shortly.

Note that, although pagmo/pygmo should work on 32-bit ARM, we have currently no way of testing this, as the main CI providers only support 64-bit ARM CPUs.

I'll close this report for now, please feel free to reopen if needed.
