### ISSUE TITLE
[FEATURE] make pygmo available for python 3.9

### ISSUE THREAD

**Issue by giovannifi** [esa/pygmo2#76]
I am trying to install the module with the command:

`pip install pygmo`

in a python 3.9 environment but I get the following error message:

```
ERROR: Could not find a version that satisfies the requirement pygmo (from versions: none)
ERROR: No matching distribution found for pygmo
```

Is there any possibility to make pymgo available for python 3.9?

thanks in advance
Giovanni

**Comment by FraserParlane** [comment]
Agreed!

**Comment by bluescarni** [comment]
I am working a new pagmo release, once that is out I'll add the pygmo2 pip builds for python 3.9 as well.

Note that pygmo2 builds for python 3.9 are available in conda.

**Comment by bluescarni** [comment]
@darioizzo is working on updating the pip builds, but we don't have an ETA yet.

**Comment by DTKx** [comment]
Hello @bluescarni ,
a word of wisdom what is the latest python version stable for pygmo? 
I was able to install via conda the pygmo on the Python 3.9.7 however I was not able to run the tests (pygmo.test.run_test_suite()) from this post I guess all 3.9 is not stable.

Many thanks in advance

**Comment by spraguecaleb** [comment]
I am facing this issue also. Using Python 3.9.7 on windows. I tried to clone and build locally with cmake, but I get an this "Error: could no load cache".

**Comment by pradyparanjpe** [comment]
python3.10 too?

**Comment by jetuk** [comment]
Is there any update on getting the latest wheels on PyPI?

**Comment by darioizzo** [comment]
We are slowly abandoning support for pypi wheels ... any reason not to use
conda?

**Comment by jetuk** [comment]
It's the method and format for Python packages endorsed by the PyPA. Conda is also not free for larger commercial organisations. 

If your reason for dropping PyPI wheels is because of the maintenance burden (which I can understand), then you (or another contributor) might consider [cibuildwheel](https://github.com/pypa/cibuildwheel). It helped my project a lot getting standard wheels built. 

Finally, it might be useful to have a statement in the README notifying users that the PyPI packages will no longer be updated if that is the policy going forward.

**Comment by matteoettam09** [comment]
+1

regular pip user, reading the documentation I tried without success to install with pip.
Maybe the [pip section here](https://esa.github.io/pygmo2/install.html#pip) should be removed from the docs?

**Comment by bluescarni** [comment]
> It's the method and format for Python packages endorsed by the PyPA.

That does not really apply to pygmo, as it's primarily a C++ project with C++ dependencies. pip is not able to understand dependencies in other languages (and it could be argued that it barely understands dependencies among python packages, but that's another discussion).

The auditwheel hack of bundling shared objects together with the compiled Python module kind of works as long as you look at a single package in isolation, but fails terribly once multiple packages start bringing in their own competing and incompatible versions of the same shared objects.

> Conda is also not free for larger commercial organisations.

My understanding is that packages on conda-forge (where pagmo/pygmo are distributed) are free to use for anyone. Could you elaborate a bit on this?

> If your reason for dropping PyPI wheels is because of the maintenance burden (which I can understand), then you (or another contributor) might consider [cibuildwheel](https://github.com/pypa/cibuildwheel). It helped my project a lot getting standard wheels built.

I am not opposed to having wheels, in fact I'd be really happy if someone stepped up and fixed/maintained them. I just don't want to do it myself, as the maintenance of the conda packages is already time consuming enough.

I skimmed a bit over the documentation of ``cibuildwheel`` and I saw no mention of integration with CMake. The difficult part of building wheels for pygmo is doing it in a way that minimises duplication with the existing (CMake-based) build system. Properly maintaining one build system is time consuming enough, having two of them to take care of would be insane :)

I have been using scikit-build with some success on the job:

https://scikit-build.readthedocs.io/en/latest/skbuild.html

It takes care of the build system duplication issue, but on the other hand it cannot solve the fundamental issue of dealing with non-Python dependencies in a safe manner (only conda or another multi-language package manager can).

> Finally, it might be useful to have a statement in the README notifying users that the PyPI packages will no longer be updated if that is the policy going forward.

I'll make sure to add some text for the next version.

**Comment by darioizzo** [comment]
#117 provides the new wheel. Will be available at the next release.
