### ISSUE TITLE
installation of pygmo2 through ccmake

### ISSUE THREAD

**Issue by missiondesignsolutions** [esa/pygmo2#77]
while configuring using ccmake i m getting error saying pagmoConfig.cmae and pagmo-config.cmae files are missing.  kindly help in this regard

**Comment by darioizzo** [comment]
You need to install pagmo first. Then those files are created and copied over the target installation dir.

When configuring pygmo, if the target installation dir is found, cmake will work.

**Comment by bluescarni** [comment]
@missiondesignsolutions 

Please read the pagmo & pygmo instructions for installation from source:

https://esa.github.io/pagmo2/install.html#installation-from-source
https://esa.github.io/pygmo2/install.html#installation-from-source

I will close this report for now, please open a new one if you have more specific questions.
