### ISSUE TITLE
[BUG] PyPI doesn't have the 2.18.0 version

### ISSUE THREAD

**Issue by yurivict** [esa/pygmo2#85]
Here: https://pypi.org/project/pygmo/

**Comment by bluescarni** [comment]
Hi @yurivict

the pip package will probably be available towards the end of the month, when the core developers are back from vacations.

**Comment by Atulsingh92** [comment]
Hello, 
need pygmo for the ESA optimize challenge. 
Cannot do pip install pygmo.
```
ERROR: Could not find a version that satisfies the requirement pygmo (from versions: none)
ERROR: No matching distribution found for pygmo
```

**Comment by a2n-s** [comment]
Hi :wave: :yum: 
it appears there is still nothing in pypi :cry: 

the only way to install `pygmo` I found to be working was to use `conda` :thinking:

**Comment by darioizzo** [comment]
https://github.com/esa/pygmo2/pull/117 (distutils based) is fixing this issue while a stable solution is developed. After merge wheels will be uploaded at the next release.
