### ISSUE TITLE
[New user question] Pass options to ipopt

### ISSUE THREAD

**Issue by a-jp** [esa/pygmo2#92]
I currently use pyomo, when using ipopt I can pass options to ipopt as follows:

```python
solver = SolverFactory('ipopt')
opts = {'halt_on_ampl_error': 'yes',
           'tol': tolerance, 'bound_relax_factor': 0.0}
results = solver.solve(model, tee=False, options=opts)
```

When using pygmo I set up the ipopt solver like this:

```python
prob = pg.problem(problem)
uda = pg.ipopt()
algo = pg.algorithm(uda)
```
How would I pass the same options to ipopt that I do when using pyomo?

Thanks,
Andy

**Comment by bluescarni** [comment]
Hi @a-jp

you can set Ipopt's options after the construction of the ``uda`` object. See the docs here for some examples:

https://esa.github.io/pygmo2/algorithms.html?highlight=ipopt#pygmo.ipopt

**Comment by a-jp** [comment]
Thanks

**Comment by bluescarni** [comment]
Feel free to come over to the gitter channel the next time you have a question:

https://gitter.im/pagmo2/Lobby

Closing the report.
