### ISSUE TITLE
[FEATURE] the fitness problem (minimal or maximum?)

### ISSUE THREAD

**Issue by kunyaoli** [esa/pygmo2#97]
Dear All：

I have a question about fitness of pygmo, Is there we deal with the multi-problem turn to minimal as default? For example, if I have two objects, one should be maximum, and the other is minimal. So, i should add "-" to my maximum object when I  define "pygmo.problem"

Thanks your response.

**Comment by bluescarni** [comment]
@kunyaoli yes that is correct.
